@REM NOME FILE BAT DOS_GIT_SALVA_TUTTO.BAT
@rem COMANDO DOS DI SALVATAGGIO
@REM per attivarlo copia quest comando
@REM 

@rem prima mi sposto per sicurezza nella cartella giusta + effettuo un controllo dir
cd C:\CASA\LINGUAGGI\HTML\PROGETTI_HTML\REACT_GUIDA_HTML_IT\react-guida-html\tutorial
dir *.bat

@rem salvo tutto con git
git add .
git commit -m "aggiornamento"
git push

exit
@REM ------------ fine bat ------------------






@REM 						COMMENTO COLLETTIVO
@REM //=======================================================================================================//
goto attivazione



// PER OTTENERE L'INDIRIZZO WEB DI GITHUB USA IL COMANDO REMOTE
//---------------------------------------------------------------------------------//

	@trova@repository@github@git@apri@indirizzo@web@apri@git_(comando git remote per ottenre l'indirizzo web) 

comando git per ottenere l'indirizzo web della repository: 
per aprire github usa git remote:

	git remote get-url origin 




---------------------------------------------------------------------------------




// VISUALIZZA IN Powershell GITHUB + VISUALIZZA IN DOS
//---------------------------------------------------------------------------------//
per aprire il browser con pawershell utilizzare il comando :
@git@add.powershell_(salvataggio veloce in pawershell)
@apri@github.in@powershell_(cmd per aprire il browser in github con powershell_)


				============================================
	Start-Process "https://github.com/icivixwalter/REACT_GUIDA_HTML_IT"

In dos puoi usare start ma viene riconosciuto anche in Powershell
@apri@github.in@dos_(cmd per aprire il browser in github con DOS)

				============================================

	start https://github.com/icivixwalter/REACT_GUIDA_HTML_IT
	
//---------------------------------------------------------------------------------//






// SALVATAGGIO VELOCE IN Powershell
//---------------------------------------------------------------------------------//
copia il comando in pawershell per eseguire il salvataggio
su git in modo veloce.
@git@salvataggio@veloce.in@powershell_(Utilizza il saltaggio veloci in Powershell)
@git@salvataggi@veloci.in@powershell_(In Powershell Utilizza il saltaggio veloci )
@salva@git@veloce  @salva@veloce.con.git


Start-Process -FilePath "C:\CASA\LINGUAGGI\HTML\PROGETTI_HTML\REACT_GUIDA_HTML_IT\react-guida-html\tutorial\DOS_GIT_SALVA_TUTTO.bat"
//---------------------------------------------------------------------------------//



// SALVATAGGIO VELOCE IN DOS
//---------------------------------------------------------------------------------//

@git@salvataggio@veloce.in@dos_(Utilizza il saltaggio veloci in dos)
@git@salvataggi@veloci.in@powershell_(In dos Utilizza il saltaggio veloci )

copia questo comando nella shell dos
					comando 1
cmd.exe 
					comando 2
call DOS_GIT_SALVA_TUTTO.BAT

//---------------------------------------------------------------------------------//

:attivazione

@REM    *** FINE  *****
@REM //=======================================================================================================//